/* ============================================================
   LAUNCH CATALOG — Phase 1
   Only games that are ACTUALLY playable are listed here.
   Per build rule: never render a card that opens an empty page.
   As new games ship, add their metadata objects here (or, once
   Supabase is wired, this file is replaced by a live query to
   the `games` table — see supabase_schema.sql).
   ============================================================ */

const GAMEHUB_CATALOG = [
  {
    id: "merge-forge",
    name: "Merge Forge",
    tagline: "Merge, upgrade, unleash the forge.",
    category: "puzzle",
    categoryLabel: "Puzzle",
    developer: "GameHub Studio",
    badge: "new",
    rating: 4.7,
    plays: "2.1k",
    icon: "🔨",
    accent: "linear-gradient(135deg,#3a2a6b,#151022)",
    path: "games/merge-forge/index.html",
    original: true
  },
  {
    id: "color-collapse",
    name: "Color Collapse",
    tagline: "Chain colors before the grid overflows.",
    category: "puzzle",
    categoryLabel: "Puzzle",
    developer: "GameHub Studio",
    badge: "hot",
    rating: 4.6,
    plays: "3.4k",
    icon: "🟣",
    accent: "linear-gradient(135deg,#1b3a5c,#0d1420)",
    path: "games/color-collapse/index.html",
    original: true
  },
  {
    id: "neon-survivor",
    name: "Neon Survivor",
    tagline: "Outlast the swarm. Upgrade or die.",
    category: "action",
    categoryLabel: "Action",
    developer: "GameHub Studio",
    badge: "top",
    rating: 4.8,
    plays: "5.0k",
    icon: "⚡",
    accent: "linear-gradient(135deg,#4a1042,#12081a)",
    path: "games/neon-survivor/index.html",
    original: true
  },
  {
    id: "shadow-dash",
    name: "Shadow Dash",
    tagline: "Switch lanes. Dash through danger.",
    category: "action",
    categoryLabel: "Action",
    developer: "GameHub Studio",
    badge: "new",
    rating: 4.5,
    plays: "1.2k",
    icon: "💨",
    accent: "linear-gradient(135deg,#241a3d,#0d0a17)",
    path: "games/shadow-dash/index.html",
    original: true
  },
  {
    id: "nitro-rush",
    name: "Nitro Rush",
    tagline: "Dodge traffic. Bank nitro. Go faster.",
    category: "racing",
    categoryLabel: "Racing",
    developer: "GameHub Studio",
    badge: "hot",
    rating: 4.6,
    plays: "1.8k",
    icon: "🏎️",
    accent: "linear-gradient(135deg,#0f2a3d,#0a0e14)",
    path: "games/nitro-rush/index.html",
    original: true
  },
  {
    id: "hoop-master",
    name: "Hoop Master",
    tagline: "Pull back, release, swish. Chain combos.",
    category: "sports",
    categoryLabel: "Sports",
    developer: "GameHub Studio",
    badge: "new",
    rating: 4.7,
    plays: "980",
    icon: "🏀",
    accent: "linear-gradient(135deg,#3d2a10,#12100a)",
    path: "games/hoop-master/index.html",
    original: true
  },
  {
    id: "sky-defender",
    name: "Sky Defender",
    tagline: "Vertical shooter. Waves, formations, boss fights.",
    category: "action",
    categoryLabel: "Action",
    developer: "GameHub Studio",
    badge: "new",
    rating: 4.6,
    plays: "870",
    icon: "🚀",
    accent: "linear-gradient(135deg,#0d1826,#070c14)",
    path: "games/sky-defender/index.html",
    original: true
  },
  {
    id: "mini-empire",
    name: "Mini Empire",
    tagline: "Build, upgrade, collect. Expand your territory.",
    category: "strategy",
    categoryLabel: "Strategy",
    developer: "GameHub Studio",
    badge: "new",
    rating: 4.5,
    plays: "640",
    icon: "🏰",
    accent: "linear-gradient(135deg,#1c2412,#0d0f0a)",
    path: "games/mini-empire/index.html",
    original: true
  },
  { id:"chess", name:"Chess", tagline:"Classic strategy, full rules, two players.", category:"strategy", categoryLabel:"Strategy", developer:"GameHub Studio", badge:null, rating:4.6, plays:"2.3k", icon:"♟️", accent:"linear-gradient(135deg,#20242f,#12141c)", path:"games/chess/index.html", original:true },
  { id:"towerdefense", name:"Tower Defense", tagline:"Place towers, hold the line, survive the waves.", category:"strategy", categoryLabel:"Strategy", developer:"GameHub Studio", badge:"hot", rating:4.7, plays:"1.9k", icon:"🏯", accent:"linear-gradient(135deg,#1a2e20,#0d150f)", path:"games/towerdefense/index.html", original:true },
  { id:"tycoon", name:"Coin Tycoon", tagline:"Grow your business empire from the ground up.", category:"strategy", categoryLabel:"Strategy", developer:"GameHub Studio", badge:null, rating:4.4, plays:"1.1k", icon:"💼", accent:"linear-gradient(135deg,#2a2410,#15120a)", path:"games/tycoon/index.html", original:true },
  { id:"targetstrike3d", name:"Target Strike 3D", tagline:"Aim, fire, clear every target in 3D.", category:"action", categoryLabel:"Action", developer:"GameHub Studio", badge:"new", rating:4.5, plays:"1.4k", icon:"🎯", accent:"linear-gradient(135deg,#2a1010,#150808)", path:"games/targetstrike3d/index.html", original:true },
  { id:"snake", name:"Snake", tagline:"Grow longer, don't hit yourself.", category:"action", categoryLabel:"Action", developer:"GameHub Studio", badge:null, rating:4.3, plays:"3.1k", icon:"🐍", accent:"linear-gradient(135deg,#10251a,#080f0a)", path:"games/snake/index.html", original:true },
  { id:"flappy", name:"Flappy Golden Bird", tagline:"Tap to fly, thread every gap.", category:"action", categoryLabel:"Action", developer:"GameHub Studio", badge:null, rating:4.2, plays:"2.8k", icon:"🐦", accent:"linear-gradient(135deg,#2a2010,#150f08)", path:"games/flappy/index.html", original:true },
  { id:"whackamole", name:"Whack-a-Mole", tagline:"Fast reflexes, faster moles.", category:"action", categoryLabel:"Action", developer:"GameHub Studio", badge:null, rating:4.1, plays:"1.6k", icon:"🔨", accent:"linear-gradient(135deg,#2a1a10,#15100a)", path:"games/whackamole/index.html", original:true },
  { id:"reaction", name:"Reaction Test", tagline:"How fast are your reflexes, really?", category:"action", categoryLabel:"Action", developer:"GameHub Studio", badge:null, rating:4.0, plays:"920", icon:"⚡", accent:"linear-gradient(135deg,#251a2a,#120a15)", path:"games/reaction/index.html", original:true },
  { id:"typingtest", name:"Typing Speed Test", tagline:"Race the clock, nail every word.", category:"action", categoryLabel:"Action", developer:"GameHub Studio", badge:null, rating:4.2, plays:"1.0k", icon:"⌨️", accent:"linear-gradient(135deg,#10202a,#081015)", path:"games/typingtest/index.html", original:true },
  { id:"bubbleshooter", name:"Bubble Shooter", tagline:"Aim, pop, chain matching bubbles.", category:"puzzle", categoryLabel:"Puzzle", developer:"GameHub Studio", badge:"hot", rating:4.6, plays:"2.0k", icon:"🫧", accent:"linear-gradient(135deg,#10202a,#0a1420)", path:"games/bubbleshooter/index.html", original:true },
  { id:"connectfour", name:"Connect Four", tagline:"Line up four before your opponent does.", category:"puzzle", categoryLabel:"Puzzle", developer:"GameHub Studio", badge:null, rating:4.4, plays:"1.5k", icon:"🔴", accent:"linear-gradient(135deg,#1a2030,#0d1018)", path:"games/connectfour/index.html", original:true },
  { id:"tictactoe", name:"Tic-Tac-Toe", tagline:"The classic, same-device two player.", category:"puzzle", categoryLabel:"Puzzle", developer:"GameHub Studio", badge:null, rating:4.0, plays:"2.5k", icon:"⭕", accent:"linear-gradient(135deg,#12141c,#0a0b10)", path:"games/tictactoe/index.html", original:true },
  { id:"slidingpuzzle", name:"Sliding Puzzle", tagline:"Slide tiles back into perfect order.", category:"puzzle", categoryLabel:"Puzzle", developer:"GameHub Studio", badge:null, rating:4.1, plays:"830", icon:"🧩", accent:"linear-gradient(135deg,#20242f,#12141c)", path:"games/slidingpuzzle/index.html", original:true },
  { id:"memory", name:"Memory Match", tagline:"Flip, remember, find every pair.", category:"puzzle", categoryLabel:"Puzzle", developer:"GameHub Studio", badge:null, rating:4.3, plays:"1.7k", icon:"🃏", accent:"linear-gradient(135deg,#2a1030,#150818)", path:"games/memory/index.html", original:true },
  { id:"simonsays", name:"Simon Says", tagline:"Watch the pattern, repeat it back.", category:"puzzle", categoryLabel:"Puzzle", developer:"GameHub Studio", badge:null, rating:4.2, plays:"760", icon:"🔴", accent:"linear-gradient(135deg,#251a30,#120d18)", path:"games/simonsays/index.html", original:true },
  { id:"wordguess", name:"Word Guess", tagline:"Crack the hidden word, letter by letter.", category:"puzzle", categoryLabel:"Puzzle", developer:"GameHub Studio", badge:null, rating:4.3, plays:"1.2k", icon:"🔤", accent:"linear-gradient(135deg,#102a20,#081510)", path:"games/wordguess/index.html", original:true },
  { id:"oddoneout", name:"Find the Odd One", tagline:"Spot what doesn't belong, fast.", category:"puzzle", categoryLabel:"Puzzle", developer:"GameHub Studio", badge:null, rating:4.0, plays:"690", icon:"🔍", accent:"linear-gradient(135deg,#2a2010,#151008)", path:"games/oddoneout/index.html", original:true },
  { id:"colormatch", name:"Match the Color", tagline:"Quick color reflex challenge.", category:"puzzle", categoryLabel:"Puzzle", developer:"GameHub Studio", badge:null, rating:4.1, plays:"810", icon:"🎨", accent:"linear-gradient(135deg,#2a1020,#150810)", path:"games/colormatch/index.html", original:true },
  { id:"mathsprint", name:"Math Sprint", tagline:"Solve fast, beat the clock.", category:"puzzle", categoryLabel:"Puzzle", developer:"GameHub Studio", badge:null, rating:4.0, plays:"590", icon:"➗", accent:"linear-gradient(135deg,#102030,#08101a)", path:"games/mathsprint/index.html", original:true },
  { id:"numberguess", name:"Guess the Number", tagline:"Narrow it down before you're out of tries.", category:"puzzle", categoryLabel:"Puzzle", developer:"GameHub Studio", badge:null, rating:3.9, plays:"640", icon:"🔢", accent:"linear-gradient(135deg,#1a2a20,#0d1510)", path:"games/numberguess/index.html", original:true },
  { id:"diceroll", name:"Dice Roll", tagline:"Simple stakes, quick rounds.", category:"puzzle", categoryLabel:"Puzzle", developer:"GameHub Studio", badge:null, rating:3.8, plays:"520", icon:"🎲", accent:"linear-gradient(135deg,#2a1a10,#151008)", path:"games/diceroll/index.html", original:true },
  { id:"rps", name:"Rock-Paper-Scissors", tagline:"Best of series against the house.", category:"puzzle", categoryLabel:"Puzzle", developer:"GameHub Studio", badge:null, rating:3.9, plays:"710", icon:"✊", accent:"linear-gradient(135deg,#10252a,#081315)", path:"games/rps/index.html", original:true },
  { id:"balloonpop", name:"Pop the Balloon", tagline:"Tap fast, don't miss a single one.", category:"action", categoryLabel:"Action", developer:"GameHub Studio", badge:null, rating:4.0, plays:"680", icon:"🎈", accent:"linear-gradient(135deg,#2a1025,#150813)", path:"games/balloonpop/index.html", original:true },
  { id:"speedracer", name:"Speed Racer", tagline:"Lane-dodge racing, quick sessions.", category:"racing", categoryLabel:"Racing", developer:"GameHub Studio", badge:null, rating:4.2, plays:"1.3k", icon:"🚗", accent:"linear-gradient(135deg,#10202a,#081015)", path:"games/speedracer/index.html", original:true },
  { id:"block-escape", name:"Block Escape", tagline:"Push every crate onto its target.", category:"puzzle", categoryLabel:"Puzzle", developer:"GameHub Studio", badge:"new", rating:4.4, plays:"430", icon:"📦", accent:"linear-gradient(135deg,#1a1e2e,#0d0f17)", path:"games/block-escape/index.html", original:true },
  { id:"robo-arena", name:"Robo Arena", tagline:"Tap to strike. Survive every wave.", category:"action", categoryLabel:"Action", developer:"GameHub Studio", badge:"new", rating:4.5, plays:"510", icon:"🤖", accent:"linear-gradient(135deg,#241414,#100a0a)", path:"games/robo-arena/index.html", original:true },
  { id:"street-drift-x", name:"Street Drift X", tagline:"Hold to drift, chain the multiplier.", category:"racing", categoryLabel:"Racing", developer:"GameHub Studio", badge:"hot", rating:4.6, plays:"470", icon:"🏁", accent:"linear-gradient(135deg,#1c0e28,#12081a)", path:"games/street-drift-x/index.html", original:true },
  { id:"cafe-rush", name:"Cafe Rush", tagline:"Serve every order before patience runs out.", category:"strategy", categoryLabel:"Strategy", developer:"GameHub Studio", badge:"new", rating:4.3, plays:"380", icon:"☕", accent:"linear-gradient(135deg,#2a1d10,#1a120a)", path:"games/cafe-rush/index.html", original:true },
  { id:"penalty-clash", name:"Penalty Clash", tagline:"Aim the corners, beat the keeper.", category:"sports", categoryLabel:"Sports", developer:"GameHub Studio", badge:"new", rating:4.4, plays:"350", icon:"⚽", accent:"linear-gradient(135deg,#12241a,#0a140a)", path:"games/penalty-clash/index.html", original:true }
];

const GAMEHUB_CATEGORIES = [
  { id: "all", label: "All" },
  { id: "puzzle", label: "🧩 Puzzle" },
  { id: "action", label: "⚔️ Action" },
  { id: "racing", label: "🏎️ Racing" },
  { id: "sports", label: "🏆 Sports" },
  { id: "strategy", label: "🏰 Strategy" }
];
